language: objective-c
osx_image: xcode8
script:
- xcodebuild test -project ReactiveSwiftRealm.xcodeproj -scheme ReactiveSwiftRealm -destination 'platform=iOS Simulator,name=iPhone 7,OS=10.0' | xcpretty -c