language: objective-c
osx_image: xcode8
script:

  - xcodebuild -scheme ReactiveSwiftRealm -workspace ReactiveSwiftRealm.xcworkspace -sdk iphonesimulator10.0 -destination 'OS=10.0,name=iPhone 7' build test
after_success:
  - bash <(curl -s https://codecov.io/bash)