language: objective-c
osx_image: xcode8
script:
  - xcodebuild -scheme ReactiveSwiftRealm -workspace ReactiveSwiftRealm.xcworkspace -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 6S' build test

after_success:
  - bash <(curl -s https://codecov.io/bash)