language: objective-c
osx_image: xcode8
before_install: true
install: true
git:
  submodules: false
before_script:
  - git submodule update --init --recursive
script:
- xcodebuild test -project ReactiveSwiftRealm.xcodeproj -scheme ReactiveSwiftRealm -destination 'platform=iOS Simulator,name=iPhone 7,OS=10.0' | xcpretty -c