language: objective-c
osx_image: xcode8.2
before_install: true
install: true
git:
  submodules: false
before_script:
  - git submodule update --init --recursive
script:
  - travis_retry script/build
xcode_workspace: ReactiveSwiftRealm.xcworkspace
matrix:
  include:
    - xcode_scheme: ReactiveSwiftRealm
      env:
        - XCODE_SDK=iphonesimulator
        - XCODE_ACTION="build-for-testing test-without-building"
        - XCODE_DESTINATION="platform=iOS Simulator,name=iPhone 6s,OS=10.1"
      before_install:
        - brew update
        - brew outdated carthage || brew upgrade carthage
      install:
        - travis_wait 2400 carthage bootstrap --platform iOS
    - xcode_scheme: ReactiveSwiftRealm
      env:
        - XCODE_SDK=iphonesimulator
        - XCODE_ACTION="build-for-testing test-without-building"
        - XCODE_DESTINATION="platform=iOS Simulator,name=iPhone 5,OS=10.1"
      before_install:
        - brew update
        - brew outdated carthage || brew upgrade carthage
      install:
        - travis_wait 2400 carthage bootstrap --platform iOS
    - script:
        - brew update
        - brew outdated carthage || brew upgrade carthage
        - carthage bootstrap --platform iOS
        - travis_wait 2400 carthage build --no-skip-current --platform iOS
      env:
        - JOB=CARTHAGE-iOS
    - script:
      - pod repo update --silent
      - pod lib lint ReactiveSwiftRealm.podspec
      env:
        - JOB=PODSPEC
after_success:
  - bash <(curl -s https://codecov.io/bash)
    
    